---
name: Pre-release checks

on:
  workflow_call:

jobs:
  check-commit-ancestor:
    name: Check commit ancestor
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6
      - name: Check commit has been pushed on origin/main
        run: |
          git fetch --quiet origin main
          git merge-base --is-ancestor HEAD origin/main
